### ISSUE TITLE
Unhandled error (undefined) when resolving

### ISSUE THREAD

**Issue by FrankFundel** [balthazar/react-native-zeroconf#121] opened 2020-04-01 11:49 UTC
Hey,
when I publish a service on my local node server, I can find and resolve it using `react-native-zeroconf` a few times, but after the 10th time or so it fails. I can find the service with `on("found")` but, when it is resolving the service I get an` Error: Unhandled error. (undefined)`. After that i connot resolve the service anymore.

![IMG_0014](https://user-images.githubusercontent.com/12829952/78133882-8573fa00-741f-11ea-99a1-772d89cc7a14.PNG)

**Comment by FrankFundel** [comment] 2020-04-01 12:28
When I add
```
    zeroconf.on("error", err => {
      console.log(err);
    });
```
I don't get the Error displayed above, but in console I get: ` -72007` and `10` and the service still does not get resolved.

**Comment by balthazar** [comment] 2020-04-21 16:36
Duplicate of #45

**Closed by balthazar** 2020-04-21 16:36 UTC
