### ISSUE TITLE
RNZeroconf is undefined

### ISSUE THREAD

**Issue by zardtomcat** [balthazar/react-native-zeroconf#71] opened 2018-10-04 16:47 UTC
Hi,

I have been trying to use **zeroconfig** with react-native (for Android) and I am keep getting an error. I get the error after I make this call:

```
**const  discover = new Zeroconf();
discover.scan('http', 'tcp', 'local.');**
```

This is the error I get:

```
undefined is not an object (evaluating 'RNZeroconf.scan')
scan
    D:\ReactNative\client1\node_modules\react-native-zeroconf\dist\index.js:81:11
<unknown>
    D:\ReactNative\client1\App.js:19:14
loadModuleImplementation
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:214:12
guardedLoadModule
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:148:36
_require
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:132:20
<unknown>
    D:\ReactNative\client1\index.js:2
loadModuleImplementation
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:214:12
guardedLoadModule
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:141:45
_require
    D:\ReactNative\client1\node_modules\metro\src\lib\polyfills\require.js:132:20
global code
```

Does anybody knows what the problem is?
Has anybody got this working on Android?

Thanks

**Comment by harrischelsea** [comment] 2018-10-08 13:30
Hi zardtomcat,

I am working with zeroconf on my react-native project. I started zeroconf scan() successfuly on android and ios, but the problem is that type = 'http' is not working on both of them. 

If you dont resolve your problem, I can send you my example. Or if you resolve it, does the 'http' work?

**Comment by zardtomcat** [comment] 2018-10-09 17:06
Hi there
No luck yet. I am working on an android app and scan doesn't work. I am using http for type. Would appreciate if you can send your example.

Thanks

**Comment by zardtomcat** [comment] 2018-10-11 08:46
Hi harrischelsea 
I am not getting anywhere with it. Would be good to see your example, if you can share it.
Thanks

**Comment by zardtomcat** [comment] 2018-10-17 22:56
Hi
It seems awfully quiet here.. Has anybody got a solution for this or knows any other package which I can use?

Thanks

**Comment by jclwong** [comment] 2018-11-27 21:58
@zardtomcat I resolve this issue installing react-native-zeroconf by going into Android Studio and running a Gradle sync #insertPlausibleReasonHere

**Comment by balthazar** [comment] 2018-12-03 14:31
Are you sure you installed your module correctly? If `RNZeroconf` if `undefined` it's most likely what the issue is.

**Comment by balthazar** [comment] 2018-12-03 14:37
Dupe of #59

**Closed** 2018-12-03 14:43 UTC
